### ISSUE TITLE
Deleting value just entered

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-Mobile#21]
Hi @dimasciput!

I think that it is a good idea to allow users to edit or delete values entered via the app (in case somebody makes a mistake). At the moment, this is not possible (or I don't know how to do it).

Just to clarify, the user should be able to edit or delete measurements that were entered by him/herself and that are not syncornized yet (so, no measurements that are already in the system).

**Comment by dimasciput** [comment]
@clau1313 yes this is not possible at the moment, will add it later. Thanks

**Comment by dimasciput** [comment]
@clau1313 I added this feature, can you try reinstall https://nightly.link/kartoza/igrac-mobile/workflows/main/main/app-release.apk.zip

**Comment by clau1313** [comment]
Good morning @dimasciput, nice, thank you! It works well when changing measurement values, however, when I want to change the type of parameter the app stops working, and when I enter again, I can see that the change was not done. For example, it happens if I enter a value of pH, but then I want to change it to EC. The same happens in the fields of abstraction (e.g. from abstraction to spring discharge). However, this doesn't happen when changing the fields of "groundwater level" (e.g from water elevation a.m.s.l. to water depth).

**Comment by dimasciput** [comment]
Morning @clau1313, thanks for the report. I have fixed this issue, please reinstall the app https://nightly.link/kartoza/igrac-mobile/workflows/main/main/app-release.apk.zip

**Comment by clau1313** [comment]
It is working fine, thanks @dimasciput
