### ISSUE TITLE
App stopped working

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-Mobile#22]
After I opened the other issue, I decided to continue checking the app in a updated version, so I downloaded it and installed in my phone... the problem is that now it doesn't open. I only see a white screen. I tried closing and open the app several times, and restarting the phone, and nothing. What can I do @dimasciput?

By the way, it seems that I am not allowed to assign issues...

**Comment by dimasciput** [comment]
@clau1313 ok will look into it today

You should be able to assign now.

**Comment by dimasciput** [comment]
Hi @clau1313 , can you try download and reinstall the app again? here's the link https://nightly.link/kartoza/igrac-mobile/workflows/main/main/app-release.apk.zip

But please uninstall the old app first.

**Comment by clau1313** [comment]
Hi @dimasciput, thanks! I think the problem was that I didn't uninstall the old app. It is working now.
