### ISSUE TITLE
Adjust text in Description box

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-Mobile#25]
Hi Dimas!

Can you please adjust the text in the description box so it starts from the upper left corner, and not in the middle of the box?

![InkedSmartSelect_20210128-103457_IgracMobile_LI](https://user-images.githubusercontent.com/36033176/106119115-1c4f3700-6155-11eb-8a0c-a5ec51323f00.jpg)

**Comment by clau1313** [comment]
Same for field "Address"

**Comment by dimasciput** [comment]
@clau1313 please reinstall

**Comment by clau1313** [comment]
Great, thanks!
