### ISSUE TITLE
Editing coordinates

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-Mobile#26]
I tried to edit the coordinates of an existing well, but the app stopped working. I tried to open it several times, but it kept closing by itself. I uninstalled, reinstalled and tried again, and the same happened, so I uninstalled and reinstalled again and stopped trying.

Beyond this error, I have a comment about this function. Users should not be allowed to edit coordinates of existing wells, but only of wells that were entered via the app and are still in the cue to be sync. 

Moreover, is it possible to add a button to modify the coordinates to the current location? I have this question because I think that it is unlikely that somebody will edit coordinates in the field by writing a new number, but this would be done by using the GPS of the phone.

**Comment by dimasciput** [comment]
> I tried to edit the coordinates of an existing well, but the app stopped working. I tried to open it several times, but it kept closing by itself. I uninstalled, reinstalled and tried again, and the same happened, so I uninstalled and reinstalled again and stopped trying.

@clau1313 I'm really sorry for this, I think it's a new bug. Will check it quickly tomorrow.

> Beyond this error, I have a comment about this function. Users should not be allowed to edit coordinates of existing wells, but only of wells that were entered via the app and are still in the cue to be sync.

Ok will do

> Moreover, is it possible to add a button to modify the coordinates to the current location? I have this question because I think that it is unlikely that somebody will edit coordinates in the field by writing a new number, but this would be done by using the GPS of the phone.

Yes it's possible, I will create a separate ticket for this.

**Comment by dimasciput** [comment]
Hi @clau1313 , I have added this feature, please try it

**Comment by clau1313** [comment]
Great, thanks!
