### ISSUE TITLE
Editing categories doesn't work

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-Mobile#27]
I tried modifying the ground surface elevation and the top borehole elevation of a random well. I can enter new values, but when I tap in "submit", nothing changes. Is this supposed to be like that because the app is only for testing, or is this function not working?

**Comment by dimasciput** [comment]
@clau1313 it must be a bug, I'll fix it later, thanks!

**Comment by dimasciput** [comment]
@clau1313 please reinstall with the updated app https://nightly.link/kartoza/igrac-mobile/workflows/main/main/app-release.apk.zip

**Comment by clau1313** [comment]
Thanks @dimasciput, it is working now.

By the way, the wells that are in the system are copies of the originals, right? because when trying the functions I am modyfing the data.

**Comment by dimasciput** [comment]
@clau1313 they are staging data, so I think it's fine if you modifying some data

**Comment by clau1313** [comment]
ok, thanks @dimasciput
