### ISSUE TITLE
Add multiple parameters of groundwater quality

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-Mobile#28]
I added new parameters of groundwater quality to a random well. First I added 3 measurements of pH, without any problem. Later, I wanted to add another parameter, but it didn't work (at least I cannot see the new values I just added). 

You can see in the image that there is only one graph displayed (for pH).

![image](https://user-images.githubusercontent.com/36033176/106150070-3d2a8300-617b-11eb-9c7b-a014bbe74443.png)

**Comment by clau1313** [comment]
Update: I tapped on "submit" and came back to the global map. Then, I tapped again into the same well, and I saw that the pH measurements dissapeared and were replaced by the measurements I thought were not saved.

**Comment by clau1313** [comment]
Update: It is the same issue for the section "abstraction/discharge"

**Comment by dimasciput** [comment]
@clau1313 you need to switch the graph by clicking the drop down
![Peek 2021-01-29 10-39](https://user-images.githubusercontent.com/1979569/106228608-53d5e600-621e-11eb-8e65-d5b55fd289ab.gif)

**Comment by clau1313** [comment]
Ohh ok! I see. Thanks @dimasciput!
