### ISSUE TITLE
Double submit button

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-Mobile#36]
When an user wants to add a new parameter to an existing well, it goes like this:

1. Select well in the map
2. tap in "view record"
3. tap in the pen icon to edit
4. go to a parameter, let's say groundwater level, and tap in "add measurement"
5. enter value and tap "submit"

After this point, it happened several times that I just tapped on the arrow at the upper left corner to come back to the map, because in my mind I already submitted the value. But, actually there is one step missing:

6. tap in "submit" again (orange button) - without this step, the values don't get stored.

Could it be that when adding measurements, only one "submit" is needed? The design doesn't need to change, it is only that after submitting the first time, the values stay there. Does it make sense?

**Comment by dimasciput** [comment]
@clau1313 I understand, will try to implement it :+1:

**Comment by dimasciput** [comment]
@clau1313 on second thought, this will introduce some confusion on some cases : 

1st use case : 
- User edit general information data
- Submit button appears
- User adds a measurement data
- User clicks submit in measurement form
- It will automatically submit the general information data and measurement data?

2nd use case : 
- User creates new lake
- The required fields are still empty, e.g. original id, name, etc
- User adds a measurement data and click submit
- The form submitted without the important fields ?

I'm actually following the igrac site for this behavior, when users add or edit measurement data in a form on the igrac site they still need to click submit.

**Comment by clau1313** [comment]
Thanks @dimasciput, I like the solution you showed us during our last meeting, Let's keep it.
