### ISSUE TITLE
Location of new well

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-Mobile#37]
When adding a new well, after tapping the icon "+", a message appears saying "select location in the map". Instead of this, a well should automatically appear at the current location. The option of selecting location in the map should be optional and not by default.

**Comment by dimasciput** [comment]
got it @clau1313 :+1:

**Comment by dimasciput** [comment]
This is added @clau1313

**Comment by clau1313** [comment]
Thanks @dimasciput. However, I find it confusing that the title of the text box is "select location on the map". What do you think if, when tapping in "+" the user goes directly to the form to submit a new well? And in the form, at the coordinates area, you have another button under "set to current location" that says "select location in the map" ?

Also, at the beginning I didn't notice that a new location was created in my location, because it appear behind another well close by. You can see it in the image below. Can you please make new wells appear above everything else?

![WhatsApp Image 2021-02-09 at 16 25 53](https://user-images.githubusercontent.com/36033176/107385964-b0c17e00-6af3-11eb-99a1-e5dbda909e63.jpeg)

**Comment by clau1313** [comment]
Sorry that image is so big, I didn't notice...

**Comment by dimasciput** [comment]
> Thanks @dimasciput. However, I find it confusing that the title of the text box is "select location on the map". What do you think if, when tapping in "+" the user goes directly to the form to submit a new well? And in the form, at the coordinates area, you have another button under "set to current location" that says "select location in the map" ?

It might be pretty difficult to add the map on the form, maybe we can simply rename the text for now? Something like "Change location by clicking on the map" ?

**Comment by dimasciput** [comment]
> @clau1313 Also, at the beginning I didn't notice that a new location was created in my location, because it appear behind another well close by. You can see it in the image below. Can you please make new wells appear above everything else?

I've updated for new data always in front, but when there are two or more markers very close each other, you have to click the marker several times to get the data you want or you need to zoom the map very close. Unfortunately this is a system limitation.

**Comment by dimasciput** [comment]
Hi @clau1313 , I added a map view in the form, so user can change the coordinate directly from the form without having to go back to map screen. Please try it.

**Comment by dimasciput** [comment]
Thanks @clau1313 , I have updated the app, please try it again.

**Comment by clau1313** [comment]
Nice! Thanks @dimasciput
