### ISSUE TITLE
We need an icon for the igrac app

### ISSUE THREAD

**Issue by dimasciput** [kartoza/IGRAC-Mobile#41]
Hi @clau1313 , do you have a suggestion on this? Or should we ask Maria to create the icon?

**Comment by clau1313** [comment]
Hi @dimasciput, this is the icon we had in the previous version of the app:

![GGMN App logo](https://user-images.githubusercontent.com/36033176/107210495-7fb65000-6a04-11eb-8495-68e35626d4ac.png)
