### ISSUE TITLE
Mandatory fields when creating new well

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-Mobile#44]
Hi @dimasciput. I was trying to create a new well, and it seems that I entered too few fields, because I got this message:

![image](https://user-images.githubusercontent.com/36033176/107387348-034f6a00-6af5-11eb-987f-e427f75415e8.png)

It would be good for the user to know which fields are mandatory, with a * for example. I thought that the mandatory fields were the ones in bold, but I managed to create a new well keeping one of the bold fields empty (feature type):

![image](https://user-images.githubusercontent.com/36033176/107387562-3e519d80-6af5-11eb-910a-f6c2cd309ed0.png)

So, why some fields are written in bold and others aren't?

Mandatory fields should be: Organisation, Original ID, Feature type and Purpose.

**Comment by dimasciput** [comment]
@clau1313 It's a bug, the bold texts are mandatory fields, I'll fix it.

**Comment by dimasciput** [comment]
This is fixed

**Comment by clau1313** [comment]
Thanks @dimasciput
