### ISSUE TITLE
I can't log in in the app

### ISSUE THREAD

**Issue by clau1313** [kartoza/IGRAC-Mobile#47]
I just installed the newest version from the main page here in GitHub, but I can't log in. First, it said that the credentials were wrong, but now it just stays loading.

**Comment by dimasciput** [comment]
Hi @clau1313 I think the staging site is still down at the moment, let me ask Irwan about this

**Comment by dimasciput** [comment]
@clau1313 should be working by now

**Comment by clau1313** [comment]
Yes it is working now
